# Generated by Django 5.0 on 2024-01-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load_json_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
